"""
GitHub PR review comment poster with diff position mapping.

Blog post: https://dadops.dev/blog/building-ai-code-review-tools/
Code Block 5.

Requires: GITHUB_TOKEN environment variable for actual PR posting.
The diff position mapper runs without any credentials.
"""
import os
import re
import sys

import requests


# ── Code Block 5: Diff Position Mapping + GitHub Review Poster ──

def map_line_to_diff_position(diff_text: str) -> dict:
    """Build a mapping from (file, line_number) to diff position."""
    position_map = {}
    current_file = None
    diff_position = 0
    current_line = 0

    for raw_line in diff_text.splitlines():
        if raw_line.startswith("+++ b/"):
            current_file = raw_line[6:]
            diff_position = 0
        elif raw_line.startswith("@@ "):
            match = re.search(r"\+(\d+)", raw_line)
            current_line = int(match.group(1)) - 1 if match else 0
            diff_position += 1
        elif current_file and diff_position > 0:
            diff_position += 1
            if not raw_line.startswith("-"):
                current_line += 1
            if raw_line.startswith("+"):
                position_map[(current_file, current_line)] = diff_position

    return position_map


def post_github_review(owner: str, repo: str, pr_number: int,
                       findings: list[dict], diff_text: str,
                       token: str, confidence_threshold: float = 0.7):
    """Post findings as inline GitHub PR review comments."""
    pos_map = map_line_to_diff_position(diff_text)
    headers = {"Authorization": f"token {token}",
               "Accept": "application/vnd.github.v3+json"}

    comments = []
    for f in findings:
        confidence = f.get("confidence", 0.8)
        if confidence < confidence_threshold:
            continue  # Skip low-confidence findings to reduce noise

        key = (f.get("file", ""), f["line"])
        position = pos_map.get(key)
        if position is None:
            continue  # Line not in diff — can't comment here

        severity_emoji = {"critical": "\U0001f534", "warning": "\U0001f7e1", "info": "\U0001f535"}
        body = (f"{severity_emoji.get(f['severity'], '\u26aa')} "
                f"**{f['severity'].upper()}** ({f['category']})\n\n"
                f"{f['description']}\n\n"
                f"**Suggestion:** {f['suggestion']}")
        comments.append({"path": f["file"], "position": position,
                         "body": body})

    if not comments:
        return None

    review_body = {
        "body": f"AI Review: {len(comments)} issue(s) found. "
                f"Review generated by automated analysis.",
        "event": "COMMENT",
        "comments": comments[:10]
    }

    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    resp = requests.post(url, json=review_body, headers=headers)
    resp.raise_for_status()
    return resp.json()


# ── Self-tests (no API key needed) ──

def test_diff_position_mapping():
    """Test the diff-to-position mapper with a synthetic diff."""
    print("=== map_line_to_diff_position Test ===")

    sample_diff = """\
--- a/app/auth.py
+++ b/app/auth.py
@@ -10,6 +10,9 @@ def authenticate(user):
     if user.is_valid():
         return True
+    # Added logging
+    log.info(f"Auth attempt: {user.name}")
+    audit_trail.record(user)
     return False

--- a/app/utils.py
+++ b/app/utils.py
@@ -1,4 +1,5 @@
 import os
+import logging

 def helper():
     pass"""

    pos_map = map_line_to_diff_position(sample_diff)
    print(f"  Position map entries: {len(pos_map)}")
    for key, pos in sorted(pos_map.items()):
        print(f"    {key[0]}:{key[1]} -> diff position {pos}")

    # Verify auth.py added lines
    assert ("app/auth.py", 12) in pos_map, "Line 12 should be mapped"
    assert ("app/auth.py", 13) in pos_map, "Line 13 should be mapped"
    assert ("app/auth.py", 14) in pos_map, "Line 14 should be mapped"

    # Verify utils.py added line
    assert ("app/utils.py", 2) in pos_map, "Line 2 should be mapped"

    print("  PASS\n")


def test_comment_filtering():
    """Test that confidence filtering and position matching work."""
    print("=== Comment Filtering Test ===")

    diff = """\
--- a/app/auth.py
+++ b/app/auth.py
@@ -10,6 +10,8 @@ def authenticate(user):
     if user.is_valid():
         return True
+    query = f"SELECT * FROM users WHERE id = {user.id}"
+    cursor.execute(query)
     return False"""

    findings = [
        {"file": "app/auth.py", "line": 12, "severity": "critical",
         "category": "security", "description": "SQL injection",
         "suggestion": "Use parameterized queries", "confidence": 0.95},
        {"file": "app/auth.py", "line": 12, "severity": "info",
         "category": "style", "description": "Consider renaming",
         "suggestion": "Use descriptive name", "confidence": 0.3},  # Below threshold
        {"file": "app/auth.py", "line": 999, "severity": "warning",
         "category": "bug", "description": "Missing check",
         "suggestion": "Add check", "confidence": 0.9},  # Not in diff
    ]

    # We can't call post_github_review without a token, but we can test filtering logic
    pos_map = map_line_to_diff_position(diff)
    kept = []
    for f in findings:
        confidence = f.get("confidence", 0.8)
        if confidence < 0.7:
            continue
        key = (f.get("file", ""), f["line"])
        if pos_map.get(key) is None:
            continue
        kept.append(f)

    print(f"  Findings in: {len(findings)}, Findings kept: {len(kept)}")
    assert len(kept) == 1, f"Expected 1 kept finding, got {len(kept)}"
    assert kept[0]["description"] == "SQL injection"
    print(f"  Kept: {kept[0]['severity']} - {kept[0]['description']}")
    print("  PASS\n")


if __name__ == "__main__":
    test_diff_position_mapping()
    test_comment_filtering()

    if os.environ.get("GITHUB_TOKEN"):
        print("GITHUB_TOKEN is set — post_github_review() is available for use.")
    else:
        print("SKIP: GITHUB_TOKEN not set — cannot post actual PR reviews.")
        print("Set GITHUB_TOKEN=ghp_... to use post_github_review().")

    print("\nAll GitHub poster tests passed!")
